module.exports = Object.freeze({"AbortController":
typeof AbortController !== 'undefined' ? AbortController : undefined,"AbortSignal":
typeof AbortController !== 'undefined' ? new AbortController().signal : undefined,"AggregateError":
typeof AggregateError !== 'undefined' ? AggregateError : undefined,"Array":
typeof Array !== 'undefined' ? Array : undefined,"Array.Iterator":
typeof [][Symbol.iterator]() !== 'undefined' ? [][Symbol.iterator]() : undefined,"ArrayBuffer":
typeof ArrayBuffer !== 'undefined' ? ArrayBuffer : undefined,"Atomics":
typeof Atomics !== 'undefined' ? Atomics : undefined,"BigInt":
typeof BigInt !== 'undefined' ? BigInt : undefined,"BigInt64Array":
typeof BigInt64Array !== 'undefined' ? BigInt64Array : undefined,"BigUint64Array":
typeof BigUint64Array !== 'undefined' ? BigUint64Array : undefined,"Boolean":
typeof Boolean !== 'undefined' ? Boolean : undefined,"Console":
typeof console !== 'undefined' ? console : undefined,"DataView":
typeof DataView !== 'undefined' ? DataView : undefined,"Date":
typeof Date !== 'undefined' ? Date : undefined,"Error":
typeof Error !== 'undefined' ? Error : undefined,"EvalError":
typeof EvalError !== 'undefined' ? EvalError : undefined,"FinalizationRegistry":
typeof FinalizationRegistry !== 'undefined' ? FinalizationRegistry : undefined,"Float32Array":
typeof Float32Array !== 'undefined' ? Float32Array : undefined,"Float64Array":
typeof Float64Array !== 'undefined' ? Float64Array : undefined,"Function":
typeof Function !== 'undefined' ? Function : undefined,"GlobalThis":
typeof globalThis !== 'undefined' ? globalThis : undefined,"Global":
typeof global !== 'undefined' ? global : undefined,"Int8Array":
typeof Int8Array !== 'undefined' ? Int8Array : undefined,"Int16Array":
typeof Int16Array !== 'undefined' ? Int16Array : undefined,"Int32Array":
typeof Int32Array !== 'undefined' ? Int32Array : undefined,"Intl":
typeof Intl !== 'undefined' ? Intl : undefined,"JSON":
typeof JSON !== 'undefined' ? JSON : undefined,"Map":
typeof Map !== 'undefined' ? Map : undefined,"Map.Iterator":
typeof Map !== 'undefined' ? new Map().values() : undefined,"Math":
typeof Math !== 'undefined' ? Math : undefined,"Number":
typeof Number !== 'undefined' ? Number : undefined,"Object":
typeof Object !== 'undefined' ? Object : undefined,"Process":
typeof process !== 'undefined' ? process : undefined,"Promise":
typeof Promise !== 'undefined' ? Promise : undefined,"RangeError":
typeof RangeError !== 'undefined' ? RangeError : undefined,"ReferenceError":
typeof ReferenceError !== 'undefined' ? ReferenceError : undefined,"RegExp":
typeof RegExp !== 'undefined' ? RegExp : undefined,"Reflect":
typeof Reflect !== 'undefined' ? Reflect : undefined,"Set":
typeof Set !== 'undefined' ? Set : undefined,"Set.Iterator":
typeof Set !== 'undefined' ? new Set().values() : undefined,"SharedArrayBuffer":
typeof SharedArrayBuffer !== 'undefined' ? SharedArrayBuffer : undefined,"String":
typeof String !== 'undefined' ? String : undefined,"String.Iterator":
typeof ""[Symbol.iterator]() !== 'undefined' ? ""[Symbol.iterator]() : undefined,"Symbol":
typeof Symbol !== 'undefined' ? Symbol : undefined,"SyntaxError":
typeof SyntaxError !== 'undefined' ? SyntaxError : undefined,"TextDecoder":
typeof TextDecoder !== 'undefined' ? TextDecoder : undefined,"TextEncoder":
typeof TextEncoder !== 'undefined' ? TextEncoder : undefined,"TypeError":
typeof TypeError !== 'undefined' ? TypeError : undefined,"Uint8Array":
typeof Uint8Array !== 'undefined' ? Uint8Array : undefined,"Uint8ClampedArray":
typeof Uint8ClampedArray !== 'undefined' ? Uint8ClampedArray : undefined,"Uint16Array":
typeof Uint16Array !== 'undefined' ? Uint16Array : undefined,"Uint32Array":
typeof Uint32Array !== 'undefined' ? Uint32Array : undefined,"URIError":
typeof URIError !== 'undefined' ? URIError : undefined,"URL":
typeof URL !== 'undefined' ? URL : undefined,"URLSearchParams":
typeof URLSearchParams !== 'undefined' ? URLSearchParams : undefined,"WeakMap":
typeof WeakMap !== 'undefined' ? WeakMap : undefined,"WeakRef":
typeof WeakRef !== 'undefined' ? WeakRef : undefined,"WeakSet":
typeof WeakSet !== 'undefined' ? WeakSet : undefined,"WebAssembly":
typeof WebAssembly !== 'undefined' ? WebAssembly : undefined,"Intl.Collator":
typeof Intl.Collator !== 'undefined' ? Intl.Collator : undefined,"Intl.DateTimeFormat":
typeof Intl.DateTimeFormat !== 'undefined' ? Intl.DateTimeFormat : undefined,"Intl.ListFormat":
typeof Intl.ListFormat !== 'undefined' ? Intl.ListFormat : undefined,"Intl.Locale":
typeof Intl.Locale !== 'undefined' ? Intl.Locale : undefined,"Intl.NumberFormat":
typeof Intl.NumberFormat !== 'undefined' ? Intl.NumberFormat : undefined,"Intl.PluralRules":
typeof Intl.PluralRules !== 'undefined' ? Intl.PluralRules : undefined,"Intl.RelativeTimeFormat":
typeof Intl.RelativeTimeFormat !== 'undefined' ? Intl.RelativeTimeFormat : undefined,"WebAssembly.Module":
typeof WebAssembly.Module !== 'undefined' ? WebAssembly.Module : undefined,"WebAssembly.Global":
typeof WebAssembly.Global !== 'undefined' ? WebAssembly.Global : undefined,"WebAssembly.Instance":
typeof WebAssembly.Instance !== 'undefined' ? WebAssembly.Instance : undefined,"WebAssembly.Memory":
typeof WebAssembly.Memory !== 'undefined' ? WebAssembly.Memory : undefined,"WebAssembly.Table":
typeof WebAssembly.Table !== 'undefined' ? WebAssembly.Table : undefined,"WebAssembly.CompileError":
typeof WebAssembly.CompileError !== 'undefined' ? WebAssembly.CompileError : undefined,"WebAssembly.LinkError":
typeof WebAssembly.LinkError !== 'undefined' ? WebAssembly.LinkError : undefined,"WebAssembly.RuntimeError":
typeof WebAssembly.RuntimeError !== 'undefined' ? WebAssembly.RuntimeError : undefined,"NaN":
typeof NaN !== 'undefined' ? NaN : undefined,"Infinity":
typeof Infinity !== 'undefined' ? Infinity : undefined,"AsyncFunction":
typeof async function(){} !== 'undefined' ? async function(){} : undefined,"AsyncGenerator":
typeof (async function*(){})() !== 'undefined' ? (async function*(){})() : undefined,"AsyncGeneratorFunction":
typeof async function*(){} !== 'undefined' ? async function*(){} : undefined,"Arguments":
typeof arguments !== 'undefined' ? arguments : undefined,"Generator":
typeof (function*(){})() !== 'undefined' ? (function*(){})() : undefined,"GeneratorFunction":
typeof function*(){} !== 'undefined' ? function*(){} : undefined,"Null":
typeof null !== 'undefined' ? null : undefined,"Undefined":
typeof undefined !== 'undefined' ? undefined : undefined})