export const Types = Object.freeze({
  AbortController: typeof AbortController !== 'undefined',
  AbortSignal: typeof new AbortController().signal !== 'undefined',
  AggregateError: typeof AggregateError !== 'undefined',
  Arguments: isArgumentsAvailable(),
  Array: typeof Array !== 'undefined',
  'Array.Iterator': typeof [][Symbol.iterator]() !== 'undefined',
  ArrayBuffer: typeof ArrayBuffer !== 'undefined',
  AsyncFunction: typeof async function () {} !== 'undefined',
  Atomics: typeof Atomics !== 'undefined',
  BigInt: typeof BigInt !== 'undefined',
  BigInt64Array: typeof BigInt64Array !== 'undefined',
  BigUint64Array: typeof BigUint64Array !== 'undefined',
  Boolean: typeof Boolean !== 'undefined',
  Console: typeof console !== 'undefined',
  DataView: typeof DataView !== 'undefined',
  Date: typeof Date !== 'undefined',
  Error: typeof Error !== 'undefined',
  EvalError: typeof EvalError !== 'undefined',
  FinalizationRegistry: typeof FinalizationRegistry !== 'undefined', // prettier-ignore
  Float32Array: typeof Float32Array !== 'undefined',
  Float64Array: typeof Float64Array !== 'undefined',
  Function: typeof Function !== 'undefined',
  Generator: typeof (function* () {})() !== 'undefined',
  GeneratorFunction: typeof function* () {} !== 'undefined',
  GlobalThis: typeof globalThis !== 'undefined',
  Global: typeof global !== 'undefined',
  Infinity: typeof Infinity !== 'undefined',
  Int8Array: typeof Int8Array !== 'undefined',
  Int16Array: typeof Int16Array !== 'undefined',
  Int32Array: typeof Int32Array !== 'undefined',
  Intl: typeof Intl !== 'undefined',
  'Intl.Collator': typeof Intl.Collator !== 'undefined',
  'Intl.DateTimeFormat': typeof Intl.DateTimeFormat !== 'undefined', // prettier-ignore
  'Intl.ListFormat': typeof Intl.ListFormat !== 'undefined',
  'Intl.Locale': typeof Intl.Locale !== 'undefined',
  'Intl.NumberFormat': typeof Intl.NumberFormat !== 'undefined',
  'Intl.PluralRules': typeof Intl.PluralRules !== 'undefined',
  'Intl.RelativeTimeFormat': typeof Intl.RelativeTimeFormat !== 'undefined', // prettier-ignore
  JSON: typeof JSON !== 'undefined',
  Map: typeof Map !== 'undefined',
  'Map.Iterator': typeof new Map().values() !== 'undefined',
  Math: typeof Math !== 'undefined',
  NaN: typeof NaN !== 'undefined',
  Null: typeof null !== 'undefined',
  Number: typeof Number !== 'undefined',
  Object: typeof Object !== 'undefined',
  Process: typeof process !== 'undefined',
  Promise: typeof Promise !== 'undefined',
  RangeError: typeof RangeError !== 'undefined',
  Reflect: typeof Reflect !== 'undefined',
  ReferenceError: typeof ReferenceError !== 'undefined',
  RegExp: typeof RegExp !== 'undefined',
  Set: typeof Set !== 'undefined',
  'Set.Iterator': typeof new Set().values() !== 'undefined',
  SharedArrayBuffer: typeof SharedArrayBuffer !== 'undefined',
  String: typeof String !== 'undefined',
  'String.Iterator': typeof ''[Symbol.iterator]() !== 'undefined',
  Symbol: typeof Symbol !== 'undefined',
  SyntaxError: typeof SyntaxError !== 'undefined',
  TextDecoder: typeof TextDecoder !== 'undefined',
  TextEncoder: typeof TextEncoder !== 'undefined',
  TypeError: typeof TypeError !== 'undefined',
  Uint8Array: typeof Uint8Array !== 'undefined',
  Uint8ClampedArray: typeof Uint8ClampedArray !== 'undefined',
  Uint16Array: typeof Uint16Array !== 'undefined',
  Uint32Array: typeof Uint32Array !== 'undefined',
  Undefined: typeof undefined === 'undefined',
  URIError: typeof URIError !== 'undefined',
  URL: typeof URL !== 'undefined',
  URLSearchParams: typeof URLSearchParams !== 'undefined',
  WeakMap: typeof WeakMap !== 'undefined',
  WeakRef: typeof WeakRef !== 'undefined',
  WeakSet: typeof WeakSet !== 'undefined',
  WebAssembly: typeof WebAssembly !== 'undefined',
  'WebAssembly.Module': typeof WebAssembly.Module !== 'undefined', // prettier-ignore
  'WebAssembly.Global': typeof WebAssembly.Global !== 'undefined', // prettier-ignore
  'WebAssembly.Instance': typeof WebAssembly.Instance !== 'undefined', // prettier-ignore
  'WebAssembly.Memory': typeof WebAssembly.Memory !== 'undefined', // prettier-ignore
  'WebAssembly.Table': typeof WebAssembly.Table !== 'undefined',
  'WebAssembly.CompileError': typeof WebAssembly.CompileError !== 'undefined', // prettier-ignore
  'WebAssembly.LinkError': typeof WebAssembly.LinkError !== 'undefined', // prettier-ignore
  'WebAssembly.RuntimeError': typeof WebAssembly.RuntimeError !== 'undefined', // prettier-ignore
  Window: typeof window !== 'undefined',
  Worker: typeof Worker !== 'undefined',
})

function isArgumentsAvailable() {
  return typeof arguments !== 'undefined' ? true : false
}
