'use strict'

export const NESTED_TYPES = [
  'Intl.Collator',
  'Intl.DateTimeFormat',
  'Intl.ListFormat',
  'Intl.Locale',
  'Intl.NumberFormat',
  'Intl.PluralRules',
  'Intl.RelativeTimeFormat',
  'WebAssembly.Module',
  'WebAssembly.Global',
  'WebAssembly.Instance',
  'WebAssembly.Memory',
  'WebAssembly.Table',
  'WebAssembly.CompileError',
  'WebAssembly.LinkError',
  'WebAssembly.RuntimeError',
]

export const NUMBER_TYPES = ['NaN', 'Infinity']

export const SYNTATIC_TYPES = [
  'AsyncFunction',
  'AsyncGenerator',
  'AsyncGeneratorFunction',
  'Arguments',
  'Generator',
  'GeneratorFunction',
  'Null',
  'Undefined',
]

export const ALL_TYPES = [
  'AbortController',
  'AbortSignal',
  'AggregateError',
  'Array',
  'Array.Iterator',
  'ArrayBuffer',
  'Atomics',
  'BigInt',
  'BigInt64Array',
  'BigUint64Array',
  'Boolean',
  'Console',
  'DataView',
  'Date',
  'Error',
  'EvalError',
  'FinalizationRegistry',
  'Float32Array',
  'Float64Array',
  'Function',
  'GlobalThis',
  'Global',
  'Int8Array',
  'Int16Array',
  'Int32Array',
  'Intl',
  'JSON',
  'Map',
  'Map.Iterator',
  'Math',
  'Number',
  'Object',
  'Process',
  'Promise',
  'RangeError',
  'ReferenceError',
  'RegExp',
  'Reflect',
  'Set',
  'Set.Iterator',
  'SharedArrayBuffer',
  'String',
  'String.Iterator',
  'Symbol',
  'SyntaxError',
  'TextDecoder',
  'TextEncoder',
  'TypeError',
  'Uint8Array',
  'Uint8ClampedArray',
  'Uint16Array',
  'Uint32Array',
  'URIError',
  'URL',
  'URLSearchParams',
  'WeakMap',
  'WeakRef',
  'WeakSet',
  'WebAssembly',
  ...NESTED_TYPES,
  ...NUMBER_TYPES,
  ...SYNTATIC_TYPES,
]

export const PRIMITIVE_TYPES = [
  'boolean',
  'string',
  'bigint',
  'number',
  'undefined',
  'symbol',
  'function',
  'null',
]
