name: TypeTags Test

on:
  pull_request:
    branches:
      - master
      - next
    paths:
      - 'lib/**'

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      __GITHUB__: true
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn test
  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn build
